/*          DISCLAIMER          *
* This was a script request. Under no circumstances is this a joke or
* a fun script. This is used for moderation, and does not represent any
* sort of offense or opinion from the author, myself. I am very sorry if
* this offended anyone, and it is not my intention to have this directed
* at anyone whatsoever. Because of the potential offensive content, the words
* list is separated from the main script.
*/
var badWords = [
	"anal",
	"anus",
	"arse",
	"ballsack",
	"bastard",
	"bitch",
	"biatch",
	"bloody",
	"blowjob",
	"blow job",
	"bollock",
	"bollok",
	"boner",
	"boob",
	"bugger",
	"butthole",
	"buttplug",
	"cameljockey",
	"chink",
	"clitoris",
	"clopclop",
	"cock",
	"coon",
	"cum",
	"cunt",
	"dick",
	"dildo",
	"dyke",
	"fag",
	"feg",
	"feck",
	"fellate",
	"fellatio",
	"felching",
	"fuck",
	"fudgepacker",
	"futa",
	"futanari",
	"flange",
	"hentai",
	"hermaphrodite",
	"Hitler",
	"jizz",
	"knobend",
	"labia",
	"nigger",
	"nigga",
	"n1gger",
	"n1gga",
	"n1gg4",
	"penis",
	"porchmonkey",
	"prick",
	"pube",
	"pussy",
	"putang",
	"queer",
	"rapist",
	"scrotum",
	"sex",
	"shit",
	"sh1t",
	"skank",
	"slut",
	"smegma",
	"spunk",
	"tosser",
	"towelhead",
	"turd",
	"twat",
	"vagina",
	"vibrator",
	"wank",
	"whore",
	"wanker",
	"wetback",
	"yaoi",
	"yiff",
	"yuri"]